name: Fuzz CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # checkout repository
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the target image
      id: push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/barbouni-2005/exim:latest

    - name: Create a directory for storing test cases
      run: mkdir -p ${{ github.workspace }}/exim-testcases

    - name: Set core pattern on the host (required for detecting crashes)
      run: echo 'core' | sudo tee /proc/sys/kernel/core_pattern

    - name: Run fuzzing campaign
      run: timeout 300 docker run --rm -v ${{ github.workspace }}/exim-testcases:/output -u $(id -u):$(id -g) ghcr.io/barbouni-2005/exim:latest || true

    - name: Compress test cases
      run: tar -czf ${{ github.workspace }}/exim-testcases.tar.gz -C ${{ github.workspace }} exim-testcases

    - name: Upload test cases as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: exim-testcases.tar.gz
        path: ${{ github.workspace }}/exim-testcases.tar.gz

